# Generated by Django 4.2.5 on 2023-09-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("shipping_status", models.CharField(max_length=50)),
                (
                    "shipping_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("shipping_payment_status", models.CharField(max_length=50)),
                ("payment_status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_perc", models.IntegerField()),
                ("tax_amt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("tracking_number", models.CharField(max_length=50)),
                ("canceled", models.CharField(max_length=1)),
                ("shipped_status_sku", models.CharField(max_length=50)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
