# Generated by Django 4.2.5 on 2023-09-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="canceled",
            new_name="Canceled",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="barcode",
            new_name="item_sid",
        ),
    ]
