name: Docker Image CI - Task1

on:
  push:
    branches: [ "task1" ]
  pull_request:
    branches: [ "task1" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8, 3.9]
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        docker network create ecommerce
        docker-compose -f docker-compose-testing.yaml up -d
        cd ecommerce_project
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        docker ps
    - name: Run Tests
      run: |
        cd ecommerce_project
        python manage.py test

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd ecommerce_project
        docker build . --file Dockerfile --tag n3ll1x/services:ecommerce-backend